global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: mysql-exporter
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: omnizap
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9102']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']

  - job_name: promtail
    static_configs:
      - targets: ['promtail:9080']
